#!/usr/bin/env bash
#this script transfers a script from a client to a server

#checking the no of arg is 4
if [ $# -lt 4 ]; then
    echo "usage: $0 transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
#using scp to transfer file
scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2:~"

fi
exit 0
