#!/usr/bin/env bash
# Install Nginx
sudo apt update -y
sudo apt install nginx -y

# Add redirection rule
sudo bash -c 'cat <<EOL >> /etc/nginx/sites-available/default
location /redirect_me {
    return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
}
EOL'

# Restart Nginx
sudo systemctl restart nginx
