#!/usr/bin/env bash
# Configures Nginx to serve a custom 404 page

# Install Nginx if not already installed
apt-get update -y
apt-get install -y nginx

# Create a custom 404 error page
echo "Ceci n'est pas une page" > /var/www/html/custom_404.html

# Modify Nginx configuration
echo "server {
    listen 80;
    server_name _;
    
    location / {
        root /var/www/html;
        index index.html index.htm;
    }

    error_page 404 /custom_404.html;
    location = /custom_404.html {
        internal;
    }
}" > /etc/nginx/sites-available/default

# Restart Nginx using the service command
service nginx restart
