# Use an official Ubuntu base image
FROM ubuntu:14.04

# Install Apache
RUN apt-get update && apt-get install -y apache2

# Create a custom HTML page
RUN echo "Hello ALX" > /var/www/html/index.html

# Expose port 80 for Apache
EXPOSE 80

# Start Apache in the foreground
CMD ["apachectl", "-D", "FOREGROUND"]
